#!/usr/bin/perl

#LICENSE:

#Please see the LICENSE file included with this distribution 
#or see the following website http://projectamin.org.

use strict;
use Amin::Protocol::Standard;
#PLEASE NOTE!!!!!
#key must be at least 8 chars

#can add 'localaddr' => 'xxx.xxx.xxx.xxx',
#to the options below for ip addresses

my $server = Amin::Protocol::Standard->new(
					{'pidfile' => 'none',
					    'localport' => '8000',
					    'logfile' => '/tmp/amindaemon-log'}, \@ARGV);
$server->Bind();

