#!/usr/bin/perl

#LICENSE:

#Please see the LICENSE file included with this distribution 
#or see the following website http://projectamin.org.

use strict;
use Amin::Protocol::Blowfish_SimpleAuth;

#PLEASE NOTE!!!!!
#Key must be at least 8 chars

my $server = Amin::Protocol::Blowfish_SimpleAuth->new('Port' => '8000',
						      'Ip' => '192.168.1.200',
						      'Key' => 'testkeys');
$server->Run();
