#!/usr/bin/perl

#LICENSE:

#Please see the LICENSE file included with this distribution 
#or see the following website http://projectamin.org.

use strict;
use Amin::Protocol::Standard;

my $server = Amin::Protocol::Standard->new(
						'Port' => '8000',
						'Ip' => '192.168.1.200',
						'Data_Store' => 'file://tmp/datastorem.xml'
					);
$server->Run();

