#!/usr/bin/perl

#xml_files convertor
use strict;
use FindBin qw($Bin);
use File::Find;

#if you have some profiles that don't use the default $search below you 
#must supply it as the argument to this program, for it to be converted right :)
#have fun


my $search = shift @ARGV;

if (!$search) {
	$search = "file://amin/xml_files";
};

my $replace = "file:/$Bin";
find(\&convert, $Bin);
print $replace;

sub convert {
	my $file = $_;
	if ($file =~ /.svn/) {next;}
	if ($file =~ /.xml/) {
		my $xmlfile = $File::Find::dir . "/" . $file;
		open (XML, "< $xmlfile");
		my @lines = <XML>;
		close (XML);
		open (XMLW, "> $xmlfile");
		foreach (@lines) {
			$_ =~ s/$search/$replace/;
			print XMLW $_;
		}
		close (XMLW);
	}
}
